### ISSUE TITLE
Create better inventory caching system

### ISSUE THREAD

**Issue by DingoDjango** [SMLHelper/SMLHelper#84]
- Separate the internal [ItemsContainerPatcher](https://github.com/SMLHelper/SMLHelper/blob/2.x/SMLHelper/Patchers/ItemsContainerPatcher.cs) into 3 distinct parts: Harmony, Helper, Interface
- Implement smart caching for storage containers
- Implement helpful methods that mods can use, outside of the game's current scope

Closes #85

**Comment by PrimeSonic** [comment]
Currently, the `HasRoomCacheCollection` of `ItemsContainerPatcher` only caches a small set of values that indicate if an item of size X_Y will fit in the container.

This likely will expand into a new class that stores this data as well as any other ItemContainer data that is useful to cache and have mods consult through a new public class in SMLHelper.

**Comment by DingoDjango** [comment]
Current suggested interface features:

`int MaxPossibleSingleSlots(ItemsContainer container);

int MaxPossibleStoredItemsForSize(ItemsContainer container, int x, int y);

int MaxPossibleStoredItemsForSize(ItemsContainer container, Vector2int size);

int FreeSingleSlotsCount(ItemsContainer container);

bool HasRoomForItemSize(IItemsContainer container, int sizeX, int sizeY);

bool HasRoomForItemSize(IItemsContainer container, Vector2int sizeVector, out bool cached);

bool ContainerEmpty(IItemsContainer container);

bool ContainerFull(IItemsContainer container);

string MainHoverText(IItemsContainer container);

string ExtraHoverText(IItemsContainer container);`

If we keep a dictionary that links containers to free slots we can extrapolate:
- Is the container full (free slots 0 or alternatively used slots == sizeX*sizeY)?
- Can an item of size (X,Y) fit inside the container?
- Expose information to mods for tooltips, etc.

Alternatively we can keep two or more caches:
- bool cache for HasRoom
- int cache for free slots
- Anything else that comes up

I do not yet know for sure if we need to change anything about the Harmony patch. It depends on how the helper method ends up looking.
