### ISSUE TITLE
Language Overrides not compatible with string.format

### ISSUE THREAD

**Issue by PrimeSonic** [SMLHelper/SMLHelper#90]
We need to select a different set of wrapping characters than `{` and `}` and these cause issues when the language line starts or ends with a `string.format` placeholder `{0}`, `{1}`,... `{#}`.  
Possibly even look into how this system might be affected when line breaks are added.

**Comment by PrimeSonic** [comment]
Reported on https://www.nexusmods.com/subnautica/mods/101/?tab=posts&jump_to_comment=68796846

**Comment by AlexejheroYTB** [comment]
Fixed in #97
